server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_jwtsecurity
    username: root
    password: vakporize
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
